[pytest]
testpaths = tests

addopts = 
    -v
    -n 2
    --reruns 1
    --html=reports/report.html
    --self-contained-html
    --cov=pages
    --cov=tests
    --cov-report=term-missing
    --cov-report=html:reports/coverage

markers =
    smoke: critical test cases
    regression: full regression suite